---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hostgroups.icinga.nexinto.com
spec:
  group: icinga.nexinto.com
  version: v1
  names:
    kind: HostGroup
    plural: hostgroups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
            vars:
              type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hosts.icinga.nexinto.com
spec:
  group: icinga.nexinto.com
  version: v1
  names:
    kind: Host
    plural: hosts
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
            vars:
              type: object
            notes:
              type: string
            notesurl:
               type: string
            hostgroups:
              type: array
              items:
                type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: checks.icinga.nexinto.com
spec:
  group: icinga.nexinto.com
  version: v1
  names:
    kind: Check
    plural: checks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
            host:
              type: string
            notes:
              type: string
            notesurl:
               type: string
            checkcommand:
              type: string
            vars:
              type: object
