---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hostgroups.icinga.nexinto.com
spec:
  group: icinga.nexinto.com
  names:
    kind: HostGroup
    plural: hostgroups
    singular: hostgroup
    shortNames:
      - hg
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                vars:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                synced:
                  type: boolean
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hosts.icinga.nexinto.com
spec:
  group: icinga.nexinto.com
  names:
    kind: Host
    plural: hosts
    singular: host
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                vars:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                notes:
                  type: string
                notesurl:
                  type: string
                hostgroups:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                synced:
                  type: boolean
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: checks.icinga.nexinto.com
spec:
  group: icinga.nexinto.com
  names:
    kind: Check
    plural: checks
    singular: check
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                host:
                  type: string
                notes:
                  type: string
                notesurl:
                  type: string
                checkcommand:
                  type: string
                vars:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                synced:
                  type: boolean
      subresources:
        status: {}