---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-icinga
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-icinga
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
- apiGroups:
  - "*"
  resources:
  - namespaces
  - pods
  - replicasets
  - daemonsets
  - deployments
  - statefulsets
  - services
  - nodes
  - componentstatuses
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - icinga.nexinto.com
  resources:
  - hostgroups
  - hostgroups/status
  - hosts
  - hosts/status
  - checks
  - checks/status
  verbs:
  - "*"
- apiGroups:
  - "*"
  resources:
  - events
  verbs:
  - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-icinga
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
subjects:
- kind: ServiceAccount
  name: kubernetes-icinga
  namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kubernetes-icinga
